# What is NumPy?

NumPy (Numerical Python) is a Python library used for fast and efficient
numerical computing.

It provides a multidimensional array called `ndarray` and many functions
for performing mathematical and scientific operations on numerical data.

## Why use NumPy instead of Python's built-in data structures?

Python lists are general-purpose data structures. They are flexible and can
store different types of objects, but they are not specifically optimized
for large-scale numerical computation.

NumPy arrays are designed specifically for numerical data. They generally
use memory more efficiently and allow mathematical operations to be
performed much faster through vectorized operations.

## Why is NumPy efficient?

Much of NumPy's core functionality is implemented in compiled low-level
code such as C. NumPy provides a Python interface on top of this
implementation, allowing us to perform efficient numerical operations
using simple Python syntax.

For example:

```python
arr = np.array([1, 2, 3, 4])

arr * 2

In [3]:
import numpy as np

In [8]:
numpy_array = np.array([1 , 2 , 3])
print(numpy_array)
print(type(numpy_array))



[1 2 3]
<class 'numpy.ndarray'>


In [12]:
nd_array = np.array([[1  , 2  , 3] , [4 , 5  , 6] ,[7 , 8 , 9]])
print(nd_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(nd_array.ndim)

2


In [21]:
three_dim_array = np.array([
    [
        [1 , 2  ,3 ] , 
        [4 , 5 , 6] , 
        [7 , 8 , 9]
    ],
    [
        [10 , 12 , 14 ],
        [15 , 16 , 18] ,
        [19 , 20 , 21]
    ],
    [
        [ 12 , 34 , 12] , 
        [34 , 89 , 90] , 
        [12 , 87 , 89] 
    ]
])

print(three_dim_array.shape)

(3, 3, 3)


# Arrange 

provide a value within a particulare range

In [30]:
array = np.arange(1,17 ) 
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [32]:
array.reshape(2 ,8 )


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

# reshape 

help to change the dimenstion of the arrary like 1d to 2d 

In [45]:
# np.arange(1 , 17).reshape(4 , 4)

np.arange(1 , 17).reshape(8 , 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])