# Mathematical Operation In Numpy 

# Scalar operation 

Performin mathematical operation (addition , substractino , multiplication or division ) between a scalar value(a singele value) and a np Array . where operaion is applied to to every element in the array 


In [2]:
import numpy as np 



In [3]:
array = np.random.random((3 ,3 ))*100
print(array.dtype)
array = array.astype("int32")
print(array.dtype)

print(array )




float64
int32
[[18 48 80]
 [65 35 86]
 [67 22 52]]


scalar operation 


In [4]:

array *2 

array([[ 36,  96, 160],
       [130,  70, 172],
       [134,  44, 104]], dtype=int32)

In [5]:
array +  2

array([[20, 50, 82],
       [67, 37, 88],
       [69, 24, 54]], dtype=int32)

In [6]:
array / 4 

array([[ 4.5 , 12.  , 20.  ],
       [16.25,  8.75, 21.5 ],
       [16.75,  5.5 , 13.  ]])

Relation operation with matrix or array 

In [7]:
array > 89


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Vector Operation 

Performin operation between given number of matices or array

In [8]:
arr_1 = np.arange(1, 17).reshape(4 , 4)
arr_2 = np.arange(17 , 33).reshape(4 , 4)

print(arr_1)
print("------")
print(arr_2)

arr_1 * arr_2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

# Important Function in Numpy for data science and machine learning 


In [9]:
# Max() calculate the max value in the given matrix or array 

print(np.max(arr_1))

16


axis ---> it provide us the max or min value arround a specific row or column 

axis = 0 ----> column wise 
axis = 1 ----> row wise

In [10]:
print(arr_1)
print(np.max(arr_1, axis=0)) # give the max value in the cloumn 
print(np.max(arr_1, axis=1)) # give the max value in the row 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[13 14 15 16]
[ 4  8 12 16]


sum() ---> calculate the sum of all the value in the arrya or matrix 

In [11]:
np.sum(arr_1 , axis=1) # sum of value row wise 

array([10, 26, 42, 58])

prod() ---> calculate the product of the all value in tht array or matrix 

In [12]:
print(np.prod(arr_1 ))
print(np.prod(arr_1 , axis=0)) # column
print(np.prod(arr_1  , axis = 1) ) # row 

20922789888000
[ 585 1680 3465 6144]
[   24  1680 11880 43680]


# Stastical function in NumPY 

mean() ---> mean of all values in the array 


In [20]:
r = np.mean(arr_1 , axis=1) # mean value for every row 
c = np.mean(arr_1 , axis = 0 ) # mean value for every column 
a = np.mean(arr_1) # mean value of entire matrix or array
print(arr_1)
print(f"mean value of every row :{r}")
print(f"mean value of every column :{c}")
print(f"mean value of entire matrix:{a}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
mean value of every row :[ 2.5  6.5 10.5 14.5]
mean value of every column :[ 7.  8.  9. 10.]
mean value of entire matrix:8.5


In [39]:
sd_array = np.array([[70 , 70 , 70 , 70 , 70]  , [30, 50, 90, 90, 110] , [0 , 0 , 0  , 0 , 0 ]])

print(sd_array)

m = np.mean(sd_array) 
print(f"Mean : {m}")
sd = np.std(sd_array , )
print(f"std : {sd}")

md = np.median(sd_array , axis=1).astype('bool')
print(md)
print(md.dtype)

[[ 70  70  70  70  70]
 [ 30  50  90  90 110]
 [  0   0   0   0   0]]
Mean : 48.0
std : 37.98245208865097
[ True  True False]
bool


standard deviation std() . calculate the sd for every values in the element . sd tell how spread a value is from the mean . 


variance() ---- > variance calculate the how spread out the data points from the mean . by taking average of squared diffrence between each data and mean 


var = (mean - x)  ^ 2 / n 

In [44]:
v = np.var(sd_array , axis = 1 ).astype("float")
s = np.std(sd_array , axis = 1 ).astype("float")
print(v )
print(s)

[  0. 864.   0.]
[ 0.         29.39387691  0.        ]


# Trignometric function 

In [47]:
print(np.sin(90))
print(np.sin(45))
print(np.sin(60))

0.8939966636005579
0.8509035245341184
-0.3048106211022167


# Dot Products

In [88]:
matrix_1 = np.round(np.random.random((3 , 4)) * 50 ).astype("int32")
matrix_2 = np.round(np.random.random((4 , 4)) * 50 ).astype("int32")
print(matrix_1)
print(matrix_2)

dp = np.dot(matrix_1 , matrix_2)
print(dp)


[[26  1 46 34]
 [43 19 34 40]
 [35 25 46 25]]
[[41 24 47 13]
 [37 23 17 17]
 [20 36 19 48]
 [29 14 20 37]]
[[3009 2779 2793 3821]
 [4306 3253 3790 3994]
 [4005 3421 3444 4013]]


log values -- -> log() calculate the log values of each and every values 

In [91]:
lg = np.log(matrix_1)
print(matrix_1)
print(lg )

np.log([10])

[[26  1 46 34]
 [43 19 34 40]
 [35 25 46 25]]
[[3.25809654 0.         3.8286414  3.52636052]
 [3.76120012 2.94443898 3.52636052 3.68887945]
 [3.55534806 3.21887582 3.8286414  3.21887582]]


array([2.30258509])

round , ciel , floor 

round --- > goes to nearest integer value 
ciel --- > goest towared smallest integer which is greater than or equal  value eg : 1.3 --- > 2 
floor --- . goes downwards ege 1.8 --- > 1 return the largest integer which is less than or equal to the given numner 

In [92]:
r  = np.round([10.8 , 9.5 , 12.3])
c  = np.ceil([10.8 , 9.5 , 12.3])
f  = np.floor([10.8 , 9.5 , 12.3])
print(f'round : ;{r}')
print(f'ceil : ;{c}')
print(f'floor : ;{f}')


round : ;[11. 10. 12.]
ceil : ;[11. 10. 13.]
floor : ;[10.  9. 12.]


transpose: np.transpose(arr)   arr[i][j] ---> arr[j][i]



In [99]:
mat = np.round(np.random.random((3 , 4)) * 20 ).astype('int32')
print(mat)

print(np.transpose(mat) )


[[12 11 18  0]
 [16  5 16 15]
 [16 12  4 10]]
[[12 16 16]
 [11  5 12]
 [18 16  4]
 [ 0 15 10]]


Ravel()---> conver a nd array into one d array 

In [ ]:
nd = np.round(np.random.random((3,3))* 50).astype('int32')
print(nd)
print(nd.ravel())

[[18 46  5]
 [ 3  8 14]
 [21 19 19]]
8
[18 46  5  3  8 14 21 19 19]


# Indexing and slicing 

In [133]:
print(nd[2,2]) # [rowNumber, columnNumber]

nd = np.round(np.random.random((4 , 4))*100 ).astype('int32')
# print(nd[0:2 , 2: ])

# Iterating over 2-D Array it will disply row by row 
# for n in nd : 
#     print(n)

three_d = np.round(np.random.random((3, 3 , 3))*100 ).astype('int32')

for i , value in enumerate(np.nditer(three_d) ):
    print(f"{i+1} : {value}")


31
1 : 57
2 : 93
3 : 87
4 : 3
5 : 44
6 : 76
7 : 99
8 : 56
9 : 89
10 : 30
11 : 90
12 : 8
13 : 3
14 : 11
15 : 42
16 : 64
17 : 44
18 : 43
19 : 97
20 : 66
21 : 77
22 : 21
23 : 94
24 : 80
25 : 22
26 : 77
27 : 36
