# Task 3 

In [10]:
import numpy as np 
values = np.array([2 , 4 , 6 , 8 , 10])

print(np.sqrt(values))


[1.41421356 2.         2.44948974 2.82842712 3.16227766]


1. Sqaure root of each element

In [11]:
print(np.sqrt(values))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


2. Exponential of each element

In [12]:
print(np.exp(values))

[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]


3. Natural logarithm of each element


In [13]:
print(np.log(values))

[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


4. Sum of all Elements 

In [14]:
print(np.sum(values))

30


5. Cumulative sum of elements 

In [15]:
print(np.cumsum(values))

[ 2  6 12 20 30]
