# Task 2 

In [2]:
import numpy as np 



In [13]:
a = np.array([10, 20 , 30 , 40])
b = np.array([1, 2 , 3 , 4])


a.shape

(4,)

1 . Addition 

In [14]:
a + b 


array([11, 22, 33, 44])

2 . Subtraction 

In [15]:
a - b 

array([ 9, 18, 27, 36])

3 . Multiplication

In [16]:
a * b 

array([ 10,  40,  90, 160])

4 . Division 

In [17]:
a / b 

array([10., 10., 10., 10.])

5 . Power

In [18]:
a ** 2 

array([ 100,  400,  900, 1600])